### ISSUE TITLE
Why not use -v option?

### ISSUE THREAD

**Issue by pwnsdx** [dougbtv/docker-asterisk#44]
Why not use -v command instead of https://github.com/dougbtv/docker-asterisk/blob/master/asterisk/13/Dockerfile#L57 to https://github.com/dougbtv/docker-asterisk/blob/master/asterisk/13/Dockerfile#L60 ? This way an user can easily add his own configuration files outside the Docker partition.

Example:
```
docker run \
--name voip \
--net=host \
-v ${HOME}/asterisk:/etc/asterisk/ \
-d \
-t dougbtv/asterisk
```

Where /home/asterisk/ contains all /etc/asterisk/ stuff.

**Comment by dougbtv** [comment]
Good recommendation, I've been mounting an `/etc/asterisk` dir myself (either data volume, or bind mount), and you can too. 

Thanks for pointing out those lines, mostly, they had been there for manual testing purposes so I could hook a soft phone up to it and experience personally how it's working, but... It always kinda nagged at me that I left an iax config in the container, which if forgotten is a liability. 

So I've gone ahead and removed that, doubly so now there there's some CI which tests the configurations. 

I'll merge these changes into master shortly.

Thanks for the eyeballs!

**Comment by dougbtv** [comment]
Ack... I realize I didn't fix it for the Asterisk 13 dockerfile, fix coming shortly.
