### ISSUE TITLE
Problem with keepalived on CoreOS

### ISSUE THREAD

**Issue by themicster** [dougbtv/docker-asterisk#53]
It seems CoreOS might not have the ipvs module loaded.

From the keepalived log:
IPVS: Can't initialize ipvs: Protocol not available

**Comment by themicster** [comment]
Nevermind, just needed to do sudo modprobe ip_vs

**Comment by dougbtv** [comment]
Hrmmm! I'm gonna try to replicate that one anyway... I hadn't seen that
before. Thanks for the heads up regardless.
