### ISSUE TITLE
Error: image library/docker_images not found

### ISSUE THREAD

**Issue by juvinski** [dougbtv/docker-asterisk#56]
Hi,

I'm trying to reproduce your environment but after a lot of issues witn CentOS 7 and now running inventory/coreos cluster_big_pull.yml and I receiving "Error: image library/docker_images not found", "stdout": "Using default tag: latest\nPulling repository docker.io/library/docker_images"

**Comment by dougbtv** [comment]
Hrmmm, where are you using Centos 7, as a base image? Also, I'll happily
take a PR if you can find where in the Ansible playbook it's asking for
that image. Thanks for opening the issue, I'm on the road at the moment and
may not be able to try to replicate it for a week plus, just fyi.

**Comment by juvinski** [comment]
Hi Doug.
CenOS are tricky.
First, Kernel doesn't have support for 9p virtualization ( This helber has done an excellent work - https://github.com/helber/coreos-carga/blob/master/docs/kvm.md based on  - http://scientificlinuxforum.org/index.php?showtopic=2858)
After that, ansiable, I had to change the coreos file inside inventory from:
ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
To
ansible_python_interpreter="/home/core/bin/python"
Now I'm dealing with this docker issue, I will update you when found a solution  for this issue

**Comment by dougbtv** [comment]
Thanks for looking into it, appreciate that a lot. sorry I'm not available
to also replicate it at the moment.
