### ISSUE TITLE
Access to the directories.

### ISSUE THREAD

**Issue by tol-iwan** [dougbtv/docker-asterisk#58]
Hello.
I use asterisk11 in Docker Sinology.
Replace some of the files /etc/asterisk/*.conf fit your requirements.
Asterisk runs. Thank you.
But I need to get access to the directory /var/spool/asterisk/monitor and /var/log/asterisk. I want to keep a record of conversations and logs.
I understand that if I connect to the Docker Sinology these directories. To record them need root access.
Asterisk runs on a user asterisk. And asterisk do not have access.
What do i do?

**Comment by dougbtv** [comment]
Two things to try, so you mount those directories as a volume right, so it's something like like

```
docker run -v /your/recordings:/var/spool/asterisk/monitor {$other_options} -it dougbtv/asterisk asterisk -rvvv
```

Give the `/your/recordings` permission on the container host loose enough permissions that the asterisk user can write to it. I believe it should be userid 1000. So you can set those permissions on the host. E.g. you could do something like

```
chown -R 1000:1000 /your/recordings
chmod -R 0755 /your/recordings
```

A more complex setup would be to create a helper container that has logic what to do with your recordings, and make a data container / docker volume that's shared between the two containers, and then the helper container makes the final move to permanent storage.
