### ISSUE TITLE
Are there any way to expose SIP ports

### ISSUE THREAD

**Issue by byteshiva** [dougbtv/docker-asterisk#60]
Are there any way to expose SIP ports for asterisk docker.

```
>     -p "11000:10000" \
>     -p "11000:10000/udp" \
>     -p "16384-16484:16384-16484/udp" \
>     -p "8021:8021" \
>     -p "8031:8031" \
```

**Comment by dougbtv** [comment]
you mean like `-p 5060:5060/udp` that should do it.

or `--net=host` to "expose everything"

**Comment by byteshiva** [comment]
I think ```--net=host``` will suffice my requirement

**Comment by byteshiva** [comment]
I did execute the following command ... but its not exposing port 5080
Instead I see port 8088 opened. 

```
8088/tcp open  radan-http
```


```
docker run --name somename-asterisk1 --net=host -d -t dougbtv/asterisk14:latest
```

**Comment by byteshiva** [comment]
I'm not able to open web interface via por 8088

![image](https://cloud.githubusercontent.com/assets/10637299/24058484/330077e0-0b71-11e7-84fa-3c62f9b33ca0.png)

**Comment by dougbtv** [comment]
8088 is used in this context for push configuration using sourcery

**Comment by dougbtv** [comment]
see http.conf in /etc/asterisk

**Comment by byteshiva** [comment]
how do i open port 5060 in docker-asterisks,  are there any configuration that I need to enable?

**Comment by dougbtv** [comment]
Read the .travis.yml to see exactly how it's tested (it makes a test call
over port 5060). Host networking will do it as mentioned earlier.
