### ISSUE TITLE
Add gettext package?

### ISSUE THREAD

**Issue by michaelkrog** [dougbtv/docker-asterisk#62]
Would it be possible to add the gettext package to the list of installed packages?

I am trying to use ARA to load users from mysql and would like to substitute variables in res_mysql.conf with environment variables set in Dockerfile(or overwritten when creating the container). However, to use envsubst the gettext package needs to be installed.

I have created my own image extending yours, but I figured others might need this as well.

**Comment by dougbtv** [comment]
That sounds way reasonable, a pull request would absolutely be welcome.
Thanks Michael

**Comment by michaelkrog** [comment]
Super.

I'll have it done when I'm back at work.
