### ISSUE TITLE
Error When Building - asterisk-core-sounds-en-gsm-1.4.24

### ISSUE THREAD

**Issue by WDC** [dougbtv/docker-asterisk#64]
```
 ---> 5927e1f7c109
Removing intermediate container 04122fb44393
Step 15/25 : RUN make install 1> /dev/null
 ---> Running in b54fabce52ce
######################################################################## 100.0%

gzip: stdin: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make[1]: *** [.asterisk-core-sounds-en-gsm-1.4.24] Error 2
make: *** [datafiles] Error 2
The command '/bin/sh -c make install 1> /dev/null' returned a non-zero code: 2
```

Is this an issue with Asterisk not serving the correct `.tar.gz`? It looks like they may be supplying a bad archive...

Thanks!

**Comment by WDC** [comment]
Resolved by adding `wget` to the `yum install` line.

Kudos to `file` on `#asterisk` at irc.freenode.com!

![image](https://cloud.githubusercontent.com/assets/1221004/25291940/0c7bd064-26a2-11e7-8f25-0bade3bffe6f.png)

**Comment by dougbtv** [comment]
Thanks for the heads up David! Appreciate the report
