### ISSUE TITLE
How to connect from X-lite?

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [dougbtv/docker-asterisk#67]
Hi!
I'm trying to connect to the Asterisk server from X-lite
Since the Asterisk container is in the same network as the host, I should be able to connect to it just by connecting to 127.0.0.1, Is this correct?

Thank you

**Comment by Stolarskis** [comment]
You need to add the signal port. I set mine to 5060, so you should put for the domain

127.0.0.1:5060

**Comment by amidia** [comment]
Hi!
can you add example for this scenario "run container and softphone on local environment". 
i tried this by run container and use zoiper + linphone to call each other on my laptop. but still unsuccessful. 
can you add what configuration on sip.conf need to be add and how to run the container it's self.

**Comment by Stolarskis** [comment]
What OS are you using?

**Comment by amidia** [comment]
DISTRIB_ID="elementary"
DISTRIB_RELEASE=0.4.1
DISTRIB_CODENAME=loki
DISTRIB_DESCRIPTION="elementary OS 0.4.1 Loki

**Comment by dougbtv** [comment]
You might also need to add the RTP ports, too. E.g. `-p 10000:10000 -p 10001:10001` etc.

**Comment by amidia** [comment]
actually yes. i can't received calls without those rtp port (need to specify the port in softphone's config too).
it's now can make call from laptop's softphone to android's handset extension, but still unable to make it the other way.

**Comment by mimusica** [comment]
@amidia  you need 2 ports per 1 call
https://stackoverflow.com/questions/56570773/how-do-i-create-docker-container-with-asterisk-16?answertab=votes#tab-top

@dougbtv this can be closed
