### ISSUE TITLE
Question: make menuselect

### ISSUE THREAD

**Issue by saidmasoud** [dougbtv/docker-asterisk#68]
In the asterisk14 Dockerfile, a large list of modules are explicitly enabled in the menuselect/menuselect command. With the current setup, does this disable all of the default modules, and explicitly enable the listed modules?

**Comment by mimusica** [comment]
@dougbtv  this question isn't valid anymore since v14 has been removed

**Comment by mimusica** [comment]
@saidmasoud https://wiki.asterisk.org/wiki/display/AST/Using+Menuselect+to+Select+Asterisk+Options
v14 has been removed from our repo since it reached its EOL.  V16 Certified LTS is now available
