### ISSUE TITLE
RTCP Transmission errors

### ISSUE THREAD

**Issue by rijnhard** [dougbtv/docker-asterisk#70]
So it looks like it's slightly affecting the running operation, registrations can sometimes fail repeatedly until like attempt 19 then it works. I get this error when I have multiple asterisk containers in a bridge network (docker-compose).

```
daf36bcbaf32*CLI> sip show peers
Name/username             Host                                    Dyn Forcerport Comedia    ACL Port     Status      Description                      
agent/agent               172.18.0.3                                  Auto (No)  No             5060     Unmonitored                                  
callee/callee             172.18.0.6                                  Auto (No)  No             5060     OK (1 ms)                                    
2 sip peers [Monitored: 1 online, 0 offline Unmonitored: 1 online, 0 offline]
[Jan 25 21:18:06] ERROR[445]: res_rtp_asterisk.c:3160 ast_rtcp_write_report: RTCP SR transmission error to 172.18.0.3:15673, rtcp halted Operation not permitted
[Jan 25 21:19:30] ERROR[445]: res_rtp_asterisk.c:3160 ast_rtcp_write_report: RTCP SR transmission error to 172.18.0.6:18921, rtcp halted Operation not permitted
[Jan 25 21:20:20] ERROR[445]: res_rtp_asterisk.c:3160 ast_rtcp_write_report: RTCP SR transmission error to 172.18.0.6:10613, rtcp halted Operation not permitted
```

According to [Asterisk Forums](http://forums.asterisk.org/viewtopic.php?p=201230) it's permissions or networking, I doubt bridge is doing anything funny, and it looks like you have all the ports open, although I'll get one of our techs to review the file again. Makes me think its permissions, which is of course always fun with docker.

Any idea?

**Comment by dougbtv** [comment]
Hey Rijnhard, what's your docker run command (or otherwise way of instantiating the containers), I'm wondering if maybe it is something with network permissions -- maybe either firewall (like iptables maybe), or otherwise. One thought is to try it with host networking, e.g. `docker run --net host [other options] dougbtv/asterisk`

**Comment by rijnhard** [comment]
I going to close this, for brevity I was being a tool. I was running a soft phone locally for testing, obviously it was trying to bind 5060 and a bunch of other ports and so was the asterisk container. I fixed this by REMOVING the `net=host` and doing a docker inspect to get the container IP and registering the soft phone to that (only because I couldn't be bothered to get consul and registrator running locally). The caveat is each time I restart the containers I need to redo that process.
