### ISSUE TITLE
Docker image too big

### ISSUE THREAD

**Issue by UnAfraid** [dougbtv/docker-asterisk#71]
Hello,

At the moment the image is very big because as you build the source you are never removing the build packages that you've installed and never gonna be used anymore.

Its over 1 gb non compressed

Can you please uninstall them after you're done with building so you can decrease the size of your image, thanks!

**Comment by dougbtv** [comment]
Absolutely agree, it's far too big -- do you have any interest in trying to get it working with a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/)? I'd happily take a pull request that can incorporate that, it should trim it down quite significantly.

**Comment by mimusica** [comment]
Try to run all commands within 1 RUN statement. This will already decrease your image size.
And!
Once you're done with the "make" command, run:
make dist-clean
to clean up the cached files

**Comment by mimusica** [comment]
I've created a pull request with the changes I made.
Now there is only 1 RUN statement in the entire file, yet it is clean and readable
Added "yum clean all" after "yum install"
And I added a "make dist-clean" after all sources where compiled

This resulted in saving almost half the previous image size ;-).

For some (to me) unknown reason Travis failed on asterisk 14. It appears that there is no /var/log/asterisk/cdr-csv/Master.csv file created. It seems rather weird as asterisk 13 passes and the folder permissions for both are the same.
@dougbtv  could you have a look at this please? And let me know if I can help.

**Comment by mimusica** [comment]
all images are just below 700MB now. If that suffices then you can close this :-)

**Comment by mimusica** [comment]
@UnAfraid the latest asterisk 16 certified lts is just under 600MB

**Comment by mimusica** [comment]
@dougbtv  this can be closed

**Comment by UnAfraid** [comment]
Great, thanks!
